name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install flake8

      - name: Run flake8
        run: |
          flake8 platforms/ run.py --max-line-length=120 --ignore=E501,W503,E128,E221,E226,E261,E303,E401
